- name: Add name to gitconfig
  community.general.git_config:
    scope: global
    name: user.name
    value: Dan Meyers

- name: Add email to gitconfig
  community.general.git_config:
    scope: global
    name: user.email
    value: d.meyers@infinitefunspace.co.uk

- name: Default rebase on pull
  community.general.git_config:
    scope: global
    name: pull.rebase
    value: 'true'

