- name: Add name to gitconfig
  community.general.git_config:
    scope: global
    name: user.name
    value: Dan Meyers

- name: Add email to gitconfig
  community.general.git_config:
    scope: global
    name: user.email
    value: d.meyers@infinitefunspace.co.uk

- name: Default rebase on pull
  community.general.git_config:
    scope: global
    name: pull.rebase
    value: 'true'

- name: P4Merge DiffTool cmd
  community.general.git_config:
    scope: global
    name: difftool.p4merge.cmd
    value: /Applications/p4merge.app/Contents/Resources/launchp4merge "$LOCAL" "$REMOTE"

- name: Use P4Merge DiffTool
  community.general.git_config:
    scope: global
    name: diff.tool
    value: p4merge

- name: P4Merge MergeTool cmd
  community.general.git_config:
    scope: global
    name: mergetool.p4merge.cmd
    value: /Applications/p4merge.app/Contents/Resources/launchp4merge "$BASE" "$LOCAL" "$REMOTE" "$MERGED"

- name: P4Merge MergeTool trust
  community.general.git_config:
    scope: global
    name: mergetool.p4merge.trustExitCode
    value: 'true'

- name: P4Merge MergeTool backups
  community.general.git_config:
    scope: global
    name: mergetool.p4merge.keepBackup
    value: 'false'

- name: P4Merge MergeTool temporaries
  community.general.git_config:
    scope: global
    name: mergetool.p4merge.keepTemporaries
    value: 'false'

- name: Use P4Merge MergeTool
  community.general.git_config:
    scope: global
    name: merge.tool
    value: p4merge
