- name: Homedir - ensure dirs exist
  ansible.builtin.file:
    path: '~/{{ item }}'
    state: directory
  loop:
    - bin
    - certs
    - etc
    - git
    - tmp

- name: Homedir - ensure secure dirs exist
  ansible.builtin.file:
    path: '~/{{ item }}'
    state: directory
    mode: 0700
  loop:
    - .gnupg
    - .ssh

- name: Homedir - checkout the homedir repo
  ansible.builtin.shell:
    chdir: ~/git
    cmd: git clone git@github.com:dancmeyers/homedir-skel.git
    creates: ~/git/homedir-skel/

- name: Homedir - link iTerm2 profile
  ansible.builtin.copy:
    src: Base.iTerm2.json
    dest: '~/Library/Application Support/iTerm2/DynamicProfiles/'

- name: Homedir - install OhMyZsh!
  ansible.builtin.shell:
    cmd: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
    creates: ~/.oh-my-zsh

- name: Homedir, but not - Set permissions for ZSH completion directories
  ansible.builtin.file:
    path: '{{ item }}'
    state: directory
    mode: 0700
  loop:
    - /usr/local/share/zsh
    - /usr/local/share/zsh/site-functions

- name: Homedir - link dotfiles in ~
  ansible.builtin.file:
    src: '~/git/homedir-skel/{{ item }}'
    path: '~/{{ item }}'
    state: link
    # Need to force as OhMyZsh will have created .zshrc as a file
    force: true
  loop:
    - .gitignore-default
    - .gitmessage
    - .inputrc
    - .tmux.conf
    - .vimrc
    - .zshrc

# Separate so we can restart on file change
- name: Homedir - configure GPG
  ansible.builtin.file:
    src: '~/git/homedir-skel/.gnupg/{{ item }}'
    dest: '~/.gnupg/{{ item }}'
    state: link
  loop:
    - gpg.conf
    - gpg-agent.conf
  notify:
    - Restart GPG agent

- name: Homedir - link relevant scripts in ~/bin
  ansible.builtin.file:
    src: '~/git/homedir-skel/bin/{{ item }}'
    path: '~/bin/{{ item }}'
    state: link
  loop:
    - update-git-repos.sh

- name: Homedir - cron refresh of git repos
  ansible.builtin.cron:
    name: Refresh git repos every 30 mins
    minute: 27,57
    job: ~/bin/update-git-repos.sh

