- name: Ensure dirs exist
  ansible.builtin.file:
    path: '~/{{ item }}'
    state: directory
  loop:
    - bin
    - certs
    - etc
    - tmp

- name: Ensure secure dirs exist
  ansible.builtin.file:
    path: '~/{{ item }}'
    state: directory
    mode: 0700
  loop:
    - .gnupg
    - .ssh

- name: Checkout the homedir repo
  ansible.builtin.shell:
    chdir: ~/git
    cmd: git clone git@github.com:dancmeyers/homedir-skel.git
    creates: ~/git/homedir-skel/

- name: iTerm2 profile
  ansible.builtin.copy:
    src: 'Base.iTerm2.json'
    dest: '~/Library/Application Support/iTerm2/DynamicProfiles/'

- name: OhMyZsh!
  ansible.builtin.shell:
    cmd: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
    creates: '~/.oh-my-zsh'

- name: Link dotfiles in ~
  ansible.builtin.file:
    src: '~/git/homedir-skel/{{ item }}'
    path: '~/{{ item }}'
    state: link
    # Need to force as OhMyZsh will have created .zshrc as a file
    force: true
  loop:
    - .gitignore-default
    - .gitmessage
    - .inputrc
    - .tmux.conf
    - .vimrc
    - .zshrc

# GPG doesn't like symlinks as config, has to be actual files
- name: Configure GPG
  ansible.builtin.copy:
    src: '~/git/homedir-skel/.gnupg/gpg.conf'
    dest: '~/.gnupg/'
    mode: 0600

- name: Configure GPG agent
  ansible.builtin.copy:
    src: '~/git/homedir-skel/.gnupg/gpg-agent.conf'
    dest: '~/.gnupg/'
    mode: 0600
  notify:
    - Restart GPG agent

- name: Link relevant scripts in ~/bin
  ansible.builtin.file:
    src: '~/git/homedir-skel/bin/{{ item }}'
    path: '~/bin/{{ item }}'
    state: link
  loop:
    - update-git-repos.sh

- name: Refresh git repos
  ansible.builtin.cron:
    name: Refresh git repos every 30 mins
    minute: 27,57
    job: ~/bin/update-git-repos.sh

