#!/usr/bin/env ansible-playbook

- hosts: localhost
  connection: local
  tasks:
    - name: Directory check
      debug:
        msg: Verify the script is being run from the directory it is in
      failed_when: not ansible_env.PWD.endswith('ansible-macos')
      tags:
        - always

- hosts: localhost
  connection: local
  roles:
    - role: base
      tags:
        - base
    - role: griffin
      tags:
        - griffin
    - role: personal
      tags:
        - personal

