- name: Setup AWS roles
  ansible.builtin.file:
    src: ~/git/banksy/dev-resources/.aws/config
    path: ~/.aws/config
    state: link

- name: Copy fonts
  ansible.builtin.copy:
    src: '{{ item }}'
    dest: '~/Library/Fonts/{{ item }}'
  loop:
    - Cambon-Bold.otf
    - CircularXX-Bold.otf
    - CircularXX-Light.otf
    - CircularXX-Regular.otf

- name: Copy Office colour set
  ansible.builtin.copy:
    src: GRIFFIN_COLORS_2020.xml
    dest: '~/Library/Group Containers/UBF8T346G9.Office/User Content.localized/Themes.localized/Theme Colors/'

- name: Add custom zsh config
  ansible.builtin.file:
    src: '{{ ansible_env.PWD }}/roles/griffin/files/010-griffin.zsh'
    path: '~/.oh-my-zsh/custom/010-griffin.zsh'
    state: link
