- name: Install - homebrew tap Clojure tools
  community.general.homebrew_tap:
    name: clojure/tools

- name: Install - homebrew tap K9s
  community.general.homebrew_tap:
    name: derailed/k9s

- name: Install - CircleCI
  community.general.homebrew:
    name: circleci

- name: Install - Clojure
  community.general.homebrew:
    name: clojure/tools/clojure

- name: Install - Docker ECR helper
  community.general.homebrew:
    name: docker-credential-helper-ecr

- name: Install - K9s
  community.general.homebrew:
    name: derailed/k9s/k9s

- name: Install - Signal
  community.general.homebrew_cask:
    name: signal

- name: Install - MS Excel
  community.general.mas:
    id: 462058435

- name: Install - MS OneNote
  community.general.mas:
    id: 784801555

- name: Install - MS Outlook
  community.general.mas:
    id: 985367838

- name: Install - MS Powerpoint
  community.general.mas:
    id: 462062816

- name: Install - MS Word
  community.general.mas:
    id: 462054704