- name: Install - homebrew tap Clojure tools
  community.general.homebrew_tap:
    name: clojure/tools

- name: Install - homebrew tap K9s
  community.general.homebrew_tap:
    name: derailed/k9s

- name: Install - Bazel
  community.general.homebrew:
    name: bazel

- name: Install - CircleCI
  community.general.homebrew:
    name: circleci

- name: Install - Clojure
  community.general.homebrew:
    name: clojure/tools/clojure

- name: /usr/local/bin (arm64)
  when: ansible_architecture == "arm64"
  become: yes
  ansible.builtin.file:
    path: /usr/local/bin
    state: directory
    mode: 0755

- name: Link - clojure (arm64)
  when: ansible_architecture == "arm64"
  become: yes
  ansible.builtin.file:
    src: /opt/homebrew/bin/clojure
    path: /usr/local/bin/clojure
    state: link

- name: Install - Docker ECR helper
  community.general.homebrew:
    name: docker-credential-helper-ecr

- name: Install - Helm
  community.general.homebrew:
    name: helm

- name: Install - K9s
  community.general.homebrew:
    name: derailed/k9s/k9s

- name: Install - AWS Vault
  community.general.homebrew_cask:
    name: aws-vault

- name: Install - Google Chrome
  community.general.homebrew_cask:
    name: google-chrome

- name: Install - MS Teams
  community.general.homebrew_cask:
    name: microsoft-teams

- name: Install - Pop
  community.general.homebrew_cask:
    name: pop

- name: Install - Postman
  community.general.homebrew_cask:
    name: postman

- name: Install - Signal
  community.general.homebrew_cask:
    name: signal

- name: Install - OpenIn
  community.general.mas:
    id: 1547147101

- name: Install - MS Excel
  community.general.mas:
    id: 462058435

- name: Install - MS OneNote
  community.general.mas:
    id: 784801555

- name: Install - MS Outlook
  community.general.mas:
    id: 985367838

- name: Install - MS Powerpoint
  community.general.mas:
    id: 462062816

- name: Install - MS Word
  community.general.mas:
    id: 462054704

- name: Install - clj-kondo (x86_64)
  when: ansible_architecture == "x86_64"
  ansible.builtin.shell:
    cmd: sh -c "$(curl -fsSL https://raw.githubusercontent.com/clj-kondo/clj-kondo/master/script/install-clj-kondo)"
    creates: /usr/local/bin/clj-kondo

- name: Install - clj-kondo (arm64)
  when: ansible_architecture == "arm64"
  ansible.builtin.shell:
    cmd: sh -c "$(curl -fsSL https://raw.githubusercontent.com/clj-kondo/clj-kondo/master/script/install-clj-kondo)" -- --dir /opt/local/bin
    creates: /opt/local/bin/clj-kondo

