- name: Install - homebrew tap Clojure tools
  community.general.homebrew_tap:
    name: clojure/tools

- name: Install - homebrew tap Hashicorp
  community.general.homebrew_tap:
    name: hashicorp/tap

- name: Install - adr-tools
  community.general.homebrew:
    name: adr-tools

- name: Install - AWS IAM Authenticator
  community.general.homebrew:
    name: aws-iam-authenticator

- name: Install - Bazelisk
  community.general.homebrew:
    name: bazelisk

- name: Install - CircleCI
  community.general.homebrew:
    name: circleci

- name: Install - Clojure
  community.general.homebrew:
    name: clojure/tools/clojure

- name: Install - gnu-tar
  community.general.homebrew:
    name: gnu-tar

- name: Install - graphviz
  community.general.homebrew:
    name: graphviz

- name: Install - Helm
  community.general.homebrew:
    name: helm

- name: Install - libsodium
  community.general.homebrew:
    name: libsodium

- name: Install - mitmproxy
  community.general.homebrew:
    name: mitmproxy

- name: Install - NodeJS
  community.general.homebrew:
    name: node@20
    state: linked

- name: Install - packer
  community.general.homebrew:
    name: hashicorp/tap/packer

- name: Install - pnpm
  community.general.homebrew:
    name: pnpm@8
    state: linked

- name: Install - Temurin
  community.general.homebrew:
    name: temurin@21

- name: Install - yarn
  community.general.homebrew:
    name: yarn

- name: Uninstall - OpenJDK
  community.general.homebrew:
    name: openjdk
    state: absent
    install_options:
      - ignore-dependencies

- name: Install - Docker
  community.general.homebrew_cask:
    name: docker

- name: Install - Docker ECR helper
  community.general.homebrew:
    name: docker-credential-helper-ecr

- name: Install - Fathom
  community.general.homebrew_cask:
    name: fathom

#- name: Install - Google Chrome
#  community.general.homebrew_cask:
#    name: google-chrome

#- name: Install - Pop
#  community.general.homebrew_cask:
#    name: pop

#- name: Install - Postman
#  community.general.homebrew_cask:
#    name: postman

- name: Install - Trailer
  community.general.homebrew_cask:
    name: trailer

- name: Install - visualvm
  community.general.homebrew_cask:
    name: visualvm

- name: Install - MeetingBar
  community.general.mas:
    id: 1532419400

- name: Install - MS Excel
  community.general.mas:
    id: 462058435

- name: Install - MS Outlook
  community.general.mas:
    id: 985367838

- name: Install - MS Powerpoint
  community.general.mas:
    id: 462062816

- name: Install - MS Word
  community.general.mas:
    id: 462054704

- name: Install - Slack
  community.general.mas:
    id: 803453959

- name: Install - Velja
  community.general.mas:
    id: 1607635845

- name: Uninstall - iMovie
  community.general.mas:
    id: 408981434
    state: absent

- name: Uninstall - Keynote
  community.general.mas:
    id: 409183694
    state: absent

- name: Uninstall - Numbers
  community.general.mas:
    id: 409203825
    state: absent

- name: Uninstall - Pages
  community.general.mas:
    id: 409201541
    state: absent

- name: Install - clj-kondo
  ansible.builtin.shell:
    cmd: sh -c "$(curl -fsSL https://raw.githubusercontent.com/clj-kondo/clj-kondo/master/script/install-clj-kondo)" -- --dir /opt/local/bin
    creates: /opt/local/bin/clj-kondo

