- name: Git - set up YubiKey SSH public key for signing config
  ansible.builtin.file:
    src: '~/git/homedir-skel/.ssh/id_rsa.yubi.pub'
    path: '~/.ssh/id_rsa.yubi.pub'
    state: link

- name: Git - configure YubiKey SSH as authorised for signing
  ansible.builtin.file:
    src: '~/git/homedir-skel/.ssh/allowed_signers'
    path: '~/.ssh/allowed_signers'
    state: link

- name: Git - name
  community.general.git_config:
    scope: global
    name: user.name
    value: Dan Meyers

- name: Git - email address
  community.general.git_config:
    scope: global
    name: user.email
    value: d.meyers@infinitefunspace.co.uk

- name: Git - SSH signing key
  community.general.git_config:
    scope: global
    name: user.signingkey
    value: ~/.ssh/id_rsa.yubi.pub

- name: Git - enable SSH signing
  community.general.git_config:
    scope: global
    name: gpg.format
    value: ssh

- name: Git - configure allowed SSH signing keys
  community.general.git_config:
    scope: global
    name: gpg.ssh.allowedSignersFile
    value: '~/.ssh/allowed_signers'

- name: Git - default exclude file
  community.general.git_config:
    scope: global
    name: core.excludesfile
    value: '~/.gitignore-default'

- name: Git - sign commits
  community.general.git_config:
    scope: global
    name: commit.gpgsign
    value: 'true'

- name: Git - commit template
  community.general.git_config:
    scope: global
    name: commit.template
    value: '~/.gitmessage'

- name: Git - sign tags
  community.general.git_config:
    scope: global
    name: tag.gpgsign
    value: 'true'

- name: Git - override default branch to match with GitHub defaults
  community.general.git_config:
    scope: global
    name: init.defaultBranch
    value: main

- name: Git - default push current
  community.general.git_config:
    scope: global
    name: push.default
    value: current

- name: Git - default rebase on pull
  community.general.git_config:
    scope: global
    name: pull.rebase
    value: 'true'

- name: Git - sync tags with origin
  community.general.git_config:
    scope: global
    name: remote.origin.tagOpt
    value: '--tags'

- name: Git - prune branches not on origin
  community.general.git_config:
    scope: global
    name: remote.origin.prune
    value: 'true'

- name: Git - don't prompt on diff
  community.general.git_config:
    scope: global
    name: difftool.prompt
    value: 'false'

- name: Git - P4Merge difftool cmd
  community.general.git_config:
    scope: global
    name: difftool.p4merge.cmd
    value: /Applications/p4merge.app/Contents/Resources/launchp4merge "$LOCAL" "$REMOTE"

- name: Git - use P4Merge difftool
  community.general.git_config:
    scope: global
    name: diff.tool
    value: p4merge

- name: Git - don't prompt on merge
  community.general.git_config:
    scope: global
    name: mergetool.prompt
    value: 'false'

- name: Git - P4Merge mergetool cmd
  community.general.git_config:
    scope: global
    name: mergetool.p4merge.cmd
    value: /Applications/p4merge.app/Contents/Resources/launchp4merge "$BASE" "$LOCAL" "$REMOTE" "$MERGED"

- name: Git - P4Merge mergetool trust
  community.general.git_config:
    scope: global
    name: mergetool.p4merge.trustExitCode
    value: 'true'

- name: Git - disable P4Merge mergetool backups
  community.general.git_config:
    scope: global
    name: mergetool.p4merge.keepBackup
    value: 'false'

- name: Git - disable P4Merge mergetool temporaries
  community.general.git_config:
    scope: global
    name: mergetool.p4merge.keepTemporaries
    value: 'false'

- name: Git - use P4Merge mergetool
  community.general.git_config:
    scope: global
    name: merge.tool
    value: p4merge

- name: Git - large file support clean
  community.general.git_config:
    scope: global
    name: filter.lfs.clean
    value: git-lfs clean %f

- name: Git - large file support smudge
  community.general.git_config:
    scope: global
    name: filter.lfs.smudge
    value: git-lfs smudge %f

- name: Git - large file support required
  community.general.git_config:
    scope: global
    name: filter.lfs.required
    value: 'true'

- name: Git - alias - push force-with-lease
  community.general.git_config:
    scope: global
    name: alias.pfl
    value: push --force-with-lease

- name: Git - alias - push notes
  community.general.git_config:
    scope: global
    name: alias.pn
    value: push origin refs/notes/*

- name: Git - alias - pretty graph log
  community.general.git_config:
    scope: global
    name: alias.log-graph
    value: log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr)%Creset' --abbrev-commit --date=relative

- name: Git - alias - log w/ notes
  community.general.git_config:
    scope: global
    name: alias.log-notes
    value: log --show-notes=*

- name: Git - rebase updates dependent branches
  community.general.git_config:
    scope: global
    name: rebase.updateRefs
    value: 'true'
