- name: Homedir - ensure dirs exist
  ansible.builtin.file:
    path: '~/{{ item }}'
    state: directory
  loop:
    - .aws
    - .local
    - bin
    - certs
    - etc
    - git
    - tmp

- name: Homedir - ensure secure dirs exist
  ansible.builtin.file:
    path: '~/{{ item }}'
    state: directory
    mode: 0700
  loop:
    - .gnupg
    - .ssh

- name: Homedir - checkout the homedir repo
  ansible.builtin.git:
    repo: git@github.com:dancmeyers/homedir-skel.git
    dest: ~/git/homedir-skel

- name: Homedir - install OhMyZsh!
  ansible.builtin.shell:
    cmd: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
    creates: ~/.oh-my-zsh

- name: Homedir - install zsh-autosuggestions plugin
  ansible.builtin.git:
    repo: git@github.com:zsh-users/zsh-autosuggestions.git
    dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
    update: false

- name: Homedir - install zsh-syntax-highlighting plugin
  ansible.builtin.git:
    repo: git@github.com:zsh-users/zsh-syntax-highlighting.git
    dest: ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
    update: false

- name: Homedir - install spaceship ZSH theme
  ansible.builtin.git:
    repo: git@github.com:spaceship-prompt/spaceship-prompt.git
    dest: ~/.oh-my-zsh/custom/themes/spaceship-prompt
    depth: 1
    update: false

- name: Homedir - link spaceship ZSH theme
  ansible.builtin.file:
    src: '~/.oh-my-zsh/custom/themes/spaceship-prompt/spaceship.zsh-theme'
    path: '~/.oh-my-zsh/custom/themes/spaceship.zsh-theme'
    state: link

- name: Homedir - link dotfiles in ~
  ansible.builtin.file:
    src: '~/git/homedir-skel/{{ item }}'
    path: '~/{{ item }}'
    state: link
    # Need to force as OhMyZsh will have created .zshrc as a file
    force: true
  loop:
    - .gitignore-default
    - .gitmessage
    - .inputrc
    - .tmux.conf
    - .vimrc
    - .zshrc

- name: Homedir - Add custom zsh config
  ansible.builtin.file:
    src: '~/git/homedir-skel/001-custom.zsh'
    path: '~/.oh-my-zsh/custom/001-custom.zsh'
    state: link

- name: Homedir - configure GPG
  ansible.builtin.file:
    src: '~/git/homedir-skel/.gnupg/gpg.conf'
    dest: '~/.gnupg/gpg.conf'
    state: link
    # Overwrite any temp version installed to get this repo down
    force: true

- name: Homedir - configure gpg-agent
  ansible.builtin.file:
    src: '~/git/homedir-skel/.gnupg/gpg-agent.conf.{{ ansible_architecture }}'
    dest: '~/.gnupg/gpg-agent.conf'
    state: link
    # Overwrite any temp version installed to get this repo down
    force: true
  notify:
    - Restart GPG agent

- name: Homedir - link relevant scripts in ~/bin
  ansible.builtin.file:
    src: '~/git/homedir-skel/bin/{{ item }}'
    path: '~/bin/{{ item }}'
    state: link
  loop:
    - update-git-repos.sh

#- name: Homedir - cron refresh of git repos
#  ansible.builtin.cron:
#    name: Refresh git repos every 30 mins
#    minute: 27,57
#    job: ~/bin/update-git-repos.sh

- name: Create dir for misc installs (Often hangs...)
  become: yes
  ansible.builtin.file:
    path: '/opt/local/bin'
    state: directory
    mode: 0755
    owner: '{{ ansible_user_id }}'
    group: 'staff'

