- name: Homedir - ensure dirs exist
  ansible.builtin.file:
    path: '~/{{ item }}'
    state: directory
  loop:
    - .aws
    - .local
    - bin
    - certs
    - etc
    - git
    - tmp

- name: Homedir - ensure secure dirs exist
  ansible.builtin.file:
    path: '~/{{ item }}'
    state: directory
    mode: 0700
  loop:
    - .gnupg
    - .ssh

- name: Homedir - checkout the homedir repo
  ansible.builtin.shell:
    cmd: git clone git@github.com:dancmeyers/homedir-skel.git ~/git
    creates: ~/git/homedir-skel/

- name: Homedir - install OhMyZsh!
  ansible.builtin.shell:
    cmd: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
    creates: ~/.oh-my-zsh

- name: Homedir - install zsh-autosuggestions plugin
  ansible.builtin.shell:
    cmd: git clone https://github.com/zsh-users/zsh-autosuggestions.git ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
    creates: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions

- name: Homedir - install zsh-syntax-highlighting plugin
  ansible.builtin.shell:
    cmd: git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
    creates: ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting

- name: Homedir, but not - Set permissions for zsh completion directories
  when: ansible_architecture == "x86_64"
  ansible.builtin.file:
    path: '{{ item }}'
    state: directory
    mode: 0700 
  loop:
    - /usr/local/share/zsh
    - /usr/local/share/zsh/site-functions

- name: Homedir, but not - remove broken _brew_cask completion link
  when: ansible_architecture == "x86_64"
  ansible.builtin.file:
    path: /usr/local/share/zsh/site-functions/_brew_cask
    state: absent

- name: Homedir - link dotfiles in ~
  ansible.builtin.file:
    src: '~/git/homedir-skel/{{ item }}'
    path: '~/{{ item }}'
    state: link
    # Need to force as OhMyZsh will have created .zshrc as a file
    force: true
  loop:
    - .gitignore-default
    - .gitmessage
    - .inputrc
    - .tmux.conf
    - .vimrc
    - .zshrc

- name: Homedir - Add custom zsh config
  ansible.builtin.file:
    src: '~/git/homedir-skel/001-custom.zsh'
    path: '~/.oh-my-zsh/custom/001-custom.zsh'
    state: link

- name: Homedir - configure GPG
  ansible.builtin.file:
    src: '~/git/homedir-skel/.gnupg/gpg.conf'
    dest: '~/.gnupg/gpg.conf'
    state: link

- name: Homedir - configure gpg-agent
  ansible.builtin.file:
    src: '~/git/homedir-skel/.gnupg/gpg-agent.conf.{{ ansible_architecture }}'
    dest: '~/.gnupg/gpg-agent.conf'
    state: link
  notify:
    - Restart GPG agent

- name: Homedir - link relevant scripts in ~/bin
  ansible.builtin.file:
    src: '~/git/homedir-skel/bin/{{ item }}'
    path: '~/bin/{{ item }}'
    state: link
  loop:
    - update-git-repos.sh

- name: Homedir - cron refresh of git repos
  ansible.builtin.cron:
    name: Refresh git repos every 30 mins
    minute: 27,57
    job: ~/bin/update-git-repos.sh

- name: Create dir for misc installs
  when: ansible_architecture == "arm64"
  become: yes
  ansible.builtin.file:
    path: '/opt/local/bin'
    state: directory
    mode: 0700
    owner: '{{ ansible_user_id }}'
    group: 'staff'


