- name: Defaults - show scrollbars
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: AppleShowScrollBars
    type: string
    value: Always

# This seems to _work_, after a reboot, but the trackpad first page menu options all show as unchecked...
- name: Defaults - enable context menu gesture?
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: ContextMenuGesture
    type: int
    value: 1

- name: Defaults - turn off swipe to change pages
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: AppleEnableMouseSwipeNavigateWithScrolls
    type: int
    value: 0

- name: Defaults - disable smart quotes on dash
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: NSAutomaticDashSubstitutionEnabled
    type: int
    value: 0

- name: Defaults - disable smart quotes on quote
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: NSAutomaticQuoteSubstitutionEnabled
    type: int
    value: 0

- name: Defaults - set mouse speed
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: com.apple.mouse.scaling
    type: float
    value: 2.5

- name: Defaults - disable force click data detectors
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: com.apple.trackpad.forceClick
    type: int
    value: 0

- name: Defaults - set trackpad speed
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: com.apple.trackpad.scaling
    type: float
    value: 2.5

- name: Defaults - enable mouse right click
  community.general.osx_defaults:
    domain: com.apple.AppleMultitouchMouse
    key: MouseButtonMode
    type: string
    value: TwoButton

- name: Defaults - trackpad tap to click
  community.general.osx_defaults:
    domain: com.apple.AppleMultitouchTrackpad
    key: Clicking
    type: int
    value: 1

- name: Defaults - trackpad right click bottom right
  community.general.osx_defaults:
    domain: com.apple.AppleMultitouchTrackpad
    key: TrackpadCornerSecondaryClick
    type: int
    value: 2

- name: Defaults - trackpad disable 2 finger 'right click'
  community.general.osx_defaults:
    domain: com.apple.AppleMultitouchTrackpad
    key: TrackpadRightClick
    type: int
    value: 0

- name: Defaults - enable exposé
  community.general.osx_defaults:
    domain: com.apple.dock
    key: showAppExposeGestureEnabled
    type: int
    value: 1

- name: Defaults - enable mouse driver right click
  community.general.osx_defaults:
    domain: com.apple.driver.AppleBluetoothMultitouch.mouse
    key: MouseButtonMode
    type: string
    value: TwoButton

- name: Defaults - trackpad driver tap to click
  community.general.osx_defaults:
    domain: com.apple.driver.AppleBluetoothMultitouch.trackpad
    key: Clicking
    type: int
    value: 1

- name: Defaults - trackpad driver right click bottom right
  community.general.osx_defaults:
    domain: com.apple.driver.AppleBluetoothMultitouch.trackpad
    key: TrackpadCornerSecondaryClick
    type: int
    value: 2

- name: Defaults - trackpad driver disable 2 finger 'right click'
  community.general.osx_defaults:
    domain: com.apple.driver.AppleBluetoothMultitouch.trackpad
    key: TrackpadRightClick
    type: int
    value: 0

- name: Defaults - set titlebar clock format
  community.general.osx_defaults:
    domain: com.apple.menuextra.clock
    key: DateFormat
    type: string
    value: EEE d MMM  HH:mm

- name: Defaults - set titlebar clock 24hr
  community.general.osx_defaults:
    domain: com.apple.menuextra.clock
    key: Show24Hour
    type: int
    value: 1

- name: Defaults - set titlebar clock show day of month
  community.general.osx_defaults:
    domain: com.apple.menuextra.clock
    key: ShowDayOfMonth
    type: int
    value: 1

- name: Defaults - set titlebar clock show day
  community.general.osx_defaults:
    domain: com.apple.menuextra.clock
    key: ShowDayOfWeek
    type: int
    value: 1

# These battery and bluetooth settings don't _actually_ work on Big Sur... Pressing the button sets the defaults, but
# setting the defaults doesn't turn on (or off) the button/menu item...
- name: Defaults - Show Bluetooth menu in titlebar
  community.general.osx_defaults:
    domain: com.apple.controlcenter
    key: NSStatusItem Visible Bluetooth
    type: int
    value: 1

- name: Defaults - Show Battery menu in titlebar
  community.general.osx_defaults:
    domain: com.apple.controlcenter
    key: NSStatusItem Visible Battery
    type: int
    value: 1

# These ones work, on Catalina
- name: Defaults - Show Bluetooth menu on titlebar
  community.general.osx_defaults:
    domain: com.apple.systemuiserver
    key: NSStatusItem Visible com.apple.menuextra.bluetooth
    type: int
    value: 1

- name: Defaults - Add Bluetooth menu details
  community.general.osx_defaults:
    domain: com.apple.systemuiserver
    key: menuExtras
    type: array
    array_add: yes
    value:
      - /System/Library/CoreServices/Menu Extras/Bluetooth.menu

- name: Defaults - Show percentage on battery in taskbar
  community.general.osx_defaults:
    domain: com.apple.menuextra.battery
    key: ShowPercent
    type: string
    # This needs to be quoted otherwise it comes out as 'True', but it's definitely a string not a boolean
    value: 'YES'

- name: Defaults - set iTerm2 preferences location
  community.general.osx_defaults:
    domain: com.googlecode.iterm2
    key: PrefsCustomFolder
    type: string
    value: '{{ ansible_env.PWD }}/roles/base/files/'
